#Use
FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/ecommerce-0.0.1-SNAPSHOT.jar .

EXPOSE 9007

ENTRYPOINT ["java","-jar","/app/ecommerce-0.0.1-SNAPSHOT.jar"]